# Generated by Django 6.0.6 on 2026-07-26 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actividad',
            old_name='iamgen',
            new_name='imagen',
        ),
    ]
