# Generated by Django 6.0.6 on 2026-07-14 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContenidoInformativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='titulo')),
                ('contenido', models.TextField(verbose_name='Contenido')),
                ('tipo', models.CharField(choices=[('noticia', 'Noticia'), ('servicio', 'Servicio'), ('ruta_atención', 'Ruta de Atención'), ('evento', 'Evento')], default='noticia', max_length=20, verbose_name='Tipo de contenido')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='informativo/', verbose_name='Imagen')),
                ('activo', models.BooleanField(default=True, verbose_name='Publicado')),
                ('destacado', models.BooleanField(default=False, verbose_name='Contenido destacadox')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de publicación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Ultima actualización')),
                ('programa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contenidos', to='programas.programa', verbose_name='Programa relacionado')),
            ],
            options={
                'verbose_name': 'Contenido Informativo',
                'verbose_name_plural': 'Contenidos Informativos',
                'db_table': 'informativo',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
