# Generated by Django 6.0.6 on 2026-07-26 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informativo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenidoinformativo',
            name='tipo',
            field=models.CharField(choices=[('noticia', 'Noticia'), ('servicio', 'Servicio'), ('ruta_atencion', 'Ruta de Atencion'), ('evento', 'Evento')], default='noticia', max_length=20, verbose_name='Tipo de contenido'),
        ),
    ]
