# Generated by Django 6.0.6 on 2026-07-14 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('armonia', 'En Armonía Contigo'), ('enlace', 'Enlace'), ('cultura', 'Gestion de cultura Universitaria'), ('deporte', 'Deporte y Recreación'), ('arte', 'Arte y Cultua')], max_length=100, unique=True, verbose_name='Nombre del programa')),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='programas/', verbose_name='Imagen del programa')),
                ('activo', models.BooleanField(default=True, verbose_name='Programa activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Ultima actualización')),
            ],
            options={
                'verbose_name': 'Programa',
                'verbose_name_plural': 'Programas',
                'db_table': 'programas',
                'ordering': ['nombre'],
            },
        ),
    ]
